---
- name: Install custom yum repositories
  # Although argument splatting is marked as deprecated:
  #
  # [DEPRECATION WARNING]: Using variables for task params is unsafe,
  # especially if the variables come from an external source like facts. This
  # feature will be removed in a future release.
  #
  # The core team had a a change of heart and it is actually being preserved:
  # https://github.com/ansible/ansible/pull/43798
  yum_repository: "{{ item }}"
  loop: "{{ libvirt_host_custom_yum_repos | default([]) }}"
  become: true

- name: Ensure libvirt packages are installed
  package:
    name: "{{ libvirt_host_libvirt_packages }}"
    state: present
  register: result
  until: result is success
  retries: 3
  become: True

# NOTE: QEMU emulators are available in EPEL.
- name: Ensure the EPEL repository is enabled
  yum:
    name: epel-release
    state: present
  register: result
  until: result is success
  retries: 3
  become: True
  when:
    - ansible_os_family == "RedHat"
    - libvirt_host_qemu_emulators | length > 0

- name: Ensure QEMU emulator packages are installed
  package:
    name: "{{ package }}"
    state: present
  with_items: "{{ libvirt_host_qemu_emulators }}"
  register: result
  until: result is success
  retries: 3
  become: True
  vars:
    package: "qemu-system-{{ item }}"
