---
- name: Include lvm role to create VG
  ansible.builtin.include_role:
    name: mrlesmithjr.manage-lvm
  when:
    - manage_lvm is defined
    - manage_lvm
    - libvirt_host_pools |  map(attribute='type') | select('match', '^lvm2$') | join(',') | length > 0

- name: Ensure libvirt dir storage pool directories exist
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode|int(base=8) }}"
    state: directory
  when: item.type == "dir"
  loop: "{{ libvirt_host_pools | flatten(levels=1) }}"
  become: True

- name: include rbd.yml
  ansible.builtin.include_tasks:
    file: rbd.yml
    apply:
      become: True
  when: item.type == "rbd"
  loop: "{{ libvirt_host_pools | flatten(levels=1) }}"

- name: Ensure libvirt storage pools are defined
  community.libvirt.virt_pool:
    name: "{{ item.name }}"
    command: define
    xml: "{{ item.xml | default(lookup('template', 'pool.xml.j2')) }}"
    uri: "{{ libvirt_host_uri | default(omit, true) }}"
  loop: "{{ libvirt_host_pools | flatten(levels=1) }}"
  become: True

- name: Check libvirt directory storage pool status
  community.libvirt.virt_pool:
    name: "{{ item.name }}"
    command: status
    uri: "{{ libvirt_host_uri | default(omit, true) }}"
  when: item.type == "dir"
  loop: "{{ libvirt_host_pools | flatten(levels=1) }}"
  become: True
  register: pool_status

- name: Ensure libvirt directory storage pools are built
  community.libvirt.virt_pool:
    name: "{{ item.item.name }}"
    command: build
    uri: "{{ libvirt_host_uri | default(omit, true) }}"
  when:
    - item is not skipped
    - item.status != "active"
  loop: "{{ pool_status.results }}"
  become: True

- name: Ensure libvirt storage pools are active
  community.libvirt.virt_pool:
    name: "{{ item.name }}"
    state: active
    uri: "{{ libvirt_host_uri | default(omit, true) }}"
  loop: "{{ libvirt_host_pools | flatten(levels=1) }}"
  become: True

- name: Ensure libvirt storage pools are started on boot
  community.libvirt.virt_pool:
    name: "{{ item.name }}"
    autostart: yes
    uri: "{{ libvirt_host_uri | default(omit, true) }}"
  loop: "{{ libvirt_host_pools | flatten(levels=1) }}"
  become: True
